version: 0.2.X
defaultTheme: auto
enablePWA: true
images:
  - /images/avatar.webp
keywords:
  - Ray
  - Technology
  - Database
app:
  title: Ray's Blog
search:
  enable: true
  type: fuse
  highlightTag: em
header:
  title:
    pre: '<i class="fas fa-code"></i>'
    name: Ray's Blog
  desktopMode: fixed
  themeChangeMode: select
footer:
  enable: true
  author: true
  hugo: false
home:
  profile:
    enable: true
    avatarURL: /images/avatar.webp
    title: Ray (@fgprodigal)
    subtitle: Love technology, love life.
    typeit: true
    social: true
  rss: 10
  posts:
    enable: true
    paginate: 10
social:
  github: fgprodigal
  Email: fgprodigal@gmail.com
  rss: true
section:
  paginate: 20
  rss: 10
page:
  ruby: true
  fraction: true
  fontawesome: true
  linkToMarkdown: true
  code:
    maxShownLines: 20
  share:
    enable: true
    Twitter: true
    Weibo: true
  toc:
    enable: true
    auto: true
typeit:
  duration: -1
